#!/usr/bin/env python3
"""Regenerate Glyphs.js from an installed Nerd Fonts symbols font.

The glyph names in the font's post table are the Nerd Fonts class names
without the "nf-" prefix (md-keg, linux-archlinux, ...), so the index is
read straight from the font rather than downloaded. Needs python-fonttools.

    tools/gen-glyphs.py [/usr/share/fonts/TTF/SymbolsNerdFont-Regular.ttf]
"""
import os
import re
import sys

from fontTools.ttLib import TTFont

FONT = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/TTF/SymbolsNerdFont-Regular.ttf"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Glyphs.js")

# Order the sets appear in the picker; logos first since they suit a menu icon.
SETS = ["linux", "dev", "fa", "fae", "md", "cod", "oct", "seti", "custom",
        "weather", "pom", "extra", "iec", "pl", "ple"]
NAME = re.compile(r"^([a-z]+)-([A-Za-z0-9_-]+)$")


def main():
    font = TTFont(FONT)
    cmap = font.getBestCmap()
    version = font["name"].getDebugName(5) or "unknown"
    rows = []
    for cp, name in cmap.items():
        m = NAME.match(name)
        if not m or m.group(1) not in SETS:
            continue
        rows.append((SETS.index(m.group(1)), name, cp))
    rows.sort()

    lines = ["%s %x" % (name, cp) for _, name, cp in rows]
    with open(OUT, "w") as f:
        f.write(".pragma library\n")
        f.write("// Generated by tools/gen-glyphs.py from %s (%s).\n"
                % (os.path.basename(FONT), version))
        f.write("// %d glyphs, one \"name hex\" pair per line. Do not edit by hand.\n" % len(lines))
        f.write("var raw = \"%s\"\n" % "\\n".join(lines))
    print("wrote %d glyphs to %s" % (len(lines), os.path.normpath(OUT)))


if __name__ == "__main__":
    main()
